### ISSUE TITLE
Request signer merge?

### ISSUE THREAD

**Issue by ticofab** [aws4s/aws4s#14]
I am the owner of this project: https://github.com/ticofab/aws-request-signer
It is a library to sign requests to AWS services, originally built for their managed ElasticSearch service.
I think it could be a useful part of this library, so if you guys are interested we could port / merge it on this project at some point?
Cheers,
Fabio

**Comment by amrhassan** [comment]
Hey Fabio.

I don't know if you've noticed but I originally used your library for signing, then I had to write my own implementation ([here](https://github.com/aws4s/aws4s/blob/master/src/main/scala/org/aws4s/RequestSigning.scala)) basing it on yours to add optional signing for s3 payloads, make it work with stream payloads and use http4s data structures instead for better type safety.

I could backport this implementation back to your library but I don't know if this will be okay with your other clients, since it adds dependencies on http4s and fs2.

**Comment by ticofab** [comment]
Hey there,
I see, cool stuff. I am going to put a link to your library, while keeping mine up and running.
It would be nice if you could add a link to mine in some "credits" section or something like that?
Cheers

**Comment by amrhassan** [comment]
Sure, done ;)
